### ISSUE TITLE
cargo build: Failed to select a version for `mobc-postgres`

### ISSUE THREAD

**Issue by ohmyarch** [importcjj/mobc#9] opened 2019-12-05 03:41 UTC
the package `xxx` depends on `mobc-postgres`, with features: `tokio` but `mobc-postgres` does not have these features.

mobc-postgres version: 0.3.0

**Comment by ohmyarch** [comment] 2019-12-05 03:44
Also tried git version, same.

**Comment by importcjj** [comment] 2019-12-05 04:55
@ohmyarch  What's your `tokio' version?

**Comment by ohmyarch** [comment] 2019-12-05 05:01
tokio = { version = "0.2.2", features = ["tcp", "sync", "time", "stream", "macros", "rt-threaded"] }

**Comment by importcjj** [comment] 2019-12-05 05:13
Thanks for the feedback. 

I found out the cause.

https://github.com/importcjj/mobc/blob/0.3.0/postgres/Cargo.toml#L15

`tokio` is not in the dependencies of `mobc-postgres`,  but I try to enable the feature `tokio/rt-threaded`.

I fixed the bug on the master branch, and a new version will be released soon.

**Comment by importcjj** [comment] 2019-12-05 05:20
@ohmyarch Try mobc-postgres `0.3.1`

**Comment by ohmyarch** [comment] 2019-12-05 08:50
It works.🎉

**Closed** 2019-12-05 08:51 UTC
